# Generated by Django 5.0.4 on 2024-04-12 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('types', models.CharField(choices=[('DR', 'Director'), ('WR', 'Writer'), ('AC', 'Actor')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('poster', models.ImageField(null=True, upload_to='media/poster/')),
                ('bg_picture', models.ImageField(null=True, upload_to='media/bg_picture/')),
                ('release_year', models.IntegerField()),
                ('mpa_rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG13', 'PG13'), ('R', 'R'), ('NC17', 'NC17')], max_length=5)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('duration', models.IntegerField()),
                ('genres', models.ManyToManyField(related_name='genres_movie', to='movies_api.genre')),
                ('directors', models.ManyToManyField(related_name='directors_movie', to='movies_api.person')),
                ('stars', models.ManyToManyField(related_name='stars_movie', to='movies_api.person')),
                ('writers', models.ManyToManyField(related_name='writers_movie', to='movies_api.person')),
            ],
        ),
    ]
