# Generated by Django 5.0.4 on 2024-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0002_alter_movie_bg_picture_alter_movie_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                blank=True, related_name="directors_movie", to="movies_api.person"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="genres_movie", to="movies_api.genre"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="stars",
            field=models.ManyToManyField(
                blank=True, related_name="stars_movie", to="movies_api.person"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="writers",
            field=models.ManyToManyField(
                blank=True, related_name="writers_movie", to="movies_api.person"
            ),
        ),
    ]
