# Generated by Django 5.0.4 on 2024-04-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0003_alter_movie_directors_alter_movie_genres_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["id"]},
        ),
    ]
