# Generated by Django 5.0.4 on 2024-04-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0004_alter_movie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="bg_picture",
            field=models.ImageField(blank=True, null=True, upload_to="bg_picture/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="poster/"),
        ),
    ]
